### ISSUE TITLE
Create Storage Plugin for s3

### ISSUE THREAD

**Issue by Rokshan2016** [bioinformatics-ua/dicoogle-learning-pack#8]
@Enet4
Hi , I went through these docs. But my question is where should I configure s3. e.g how to provide s3 config, access + secret key.   
https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/developing-plugins/
If I can get an example on this , that will be really helpful

Appreciated!

**Comment by Enet4** [comment]
This is a very old question, but in case there someone stumbles upon this, the answer is that the plugin-level settings are often a good place for such configuration properties, but you can also choose to inspect JVM properties or environment variables. Dicoogle plugins can obtain these details from any of these places.

Other than that, there is no S3 plugin for Dicoogle that I know of, because an easier way to store and retrieve DICOM data on AWS S3 is to mount the s3 volume into the file system and then use the filestorage plugin.
